// <auto-generated />
using BlazorFullStackCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorFullStackCrud.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230110013207_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorFullStackCrud.Shared.Buku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Judul_Buku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penerbit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penulis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Buku");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            GenreId = 1,
                            Judul_Buku = "Dear Nathan",
                            Penerbit = "Tere",
                            Penulis = "Tere Liye"
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 2,
                            Judul_Buku = "Dilan 1991",
                            Penerbit = "Pidi Baiq",
                            Penulis = "Pidi"
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 3,
                            Judul_Buku = "Dibalik 98",
                            Penerbit = "Ismail",
                            Penulis = "Ismail Marzuki"
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 4,
                            Judul_Buku = "Kisah Tanah Jawa",
                            Penerbit = "Ismail",
                            Penulis = "Ismail Marzuki"
                        },
                        new
                        {
                            Id = 56,
                            GenreId = 5,
                            Judul_Buku = "Dilannnn",
                            Penerbit = "Ismail",
                            Penulis = "Ismail Marzuki"
                        });
                });

            modelBuilder.Entity("BlazorFullStackCrud.Shared.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Horor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantasi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Edukasi"
                        });
                });

            modelBuilder.Entity("BlazorFullStackCrud.Shared.Buku", b =>
                {
                    b.HasOne("BlazorFullStackCrud.Shared.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
